name: test

on:
  #push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        label:
          - el8
        include:
          - label: el8
            container: centos:8
            install-dependency: dnf install -y python3 rsync which
    
    container:
      image: ${{ matrix.container }}
    
    steps:
      - uses: actions/checkout@v3

      - name: Some hacks for CentOS 8 (EOL) to work again.
        if: ${{ matrix.label == 'el8' }}
        run: |
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
          yum upgrade -y
          yum clean all && yum makecache
          yum distro-sync -y --allowerasing
          
      - name: Extra repos for CentOS8
        if: ${{ matrix.label == 'el8' }}
        run: |
         echo '[ltb-project]'                                              >  /etc/yum.repos.d/ltb-project.repo
         echo 'name=LTB project packages'                                  >> /etc/yum.repos.d/ltb-project.repo
         echo 'baseurl=https://ltb-project.org/rpm/$releasever/$basearch'  >> /etc/yum.repos.d/ltb-project.repo
         echo 'enabled=1'                                                  >> /etc/yum.repos.d/ltb-project.repo
         echo 'gpgcheck=1'                                                 >> /etc/yum.repos.d/ltb-project.repo
         echo 'gpgkey=https://www.ltb-project.org/documentation/_static/RPM-GPG-KEY-LTB-project' >> /etc/yum.repos.d/ltb-project.repo
         rpm --import https://www.ltb-project.org/documentation/_static/RPM-GPG-KEY-LTB-project
         yum install -y epel-release

      - name: Enable PowerTools on CentOS 8.
        if: ${{ matrix.label == 'el8' }}
        run: |
          yum install -y yum-utils wget
          yum config-manager --enable PowerTools || :
          
      - name: Install dependencies
        run: ${{ matrix.install-dependency }}

      - name: prepare Build reaf
        run: |
          pip3 install pyYAML fire filelock prettytable python-dateutil toml setuptools wcwidth wheel termcolor six
          
      - name: Coral Build
        run: |
          wget -O /var/log/coral/build_cache/open/iso_cache/lustre_release/RPMS/x86_64/lustre-devel-2.15.5-1.el8.x86_64.rpm https://downloads.whamcloud.com/public/lustre/lustre-2.15.5/el8.10/server/RPMS/x86_64/lustre-devel-2.15.5-1.el8.x86_64.rpm --no-check-certificate
          wget -O /var/log/coral/build_cache/open/iso_cache/lustre_release/RPMS/x86_64/kernel-4.18.0-553.5.1.el8_lustre.x86_64.rpm https://downloads.whamcloud.com/public/lustre/lustre-2.15.5/el8.10/server/RPMS/x86_64/kernel-4.18.0-553.5.1.el8_lustre.x86_64.rpm --no-check-certificate
          wget -O /var/log/coral/build_cache/open/iso_cache/lustre_release/RPMS/x86_64/kmod-lustre-osd-ldiskfs-2.15.5-1.el8.x86_64.rpm https://downloads.whamcloud.com/public/lustre/lustre-2.15.5/el8.10/server/RPMS/x86_64/kmod-lustre-osd-ldiskfs-2.15.5-1.el8.x86_64.rpm --no-check-certificate
          wget -O /var/log/coral/build_cache/open/iso_cache/lustre_release/RPMS/x86_64/lustre-osd-ldiskfs-mount-2.15.5-1.el8.x86_64.rpm https://downloads.whamcloud.com/public/lustre/lustre-2.15.5/el8.10/server/RPMS/x86_64/lustre-osd-ldiskfs-mount-2.15.5-1.el8.x86_64.rpm --no-check-certificate
          wget -O /var/log/coral/build_cache/open/iso_cache/lustre_release/RPMS/x86_64/kernel-modules-4.18.0-553.5.1.el8_lustre.x86_64.rpm https://downloads.whamcloud.com/public/lustre/lustre-2.15.5/el8.10/server/RPMS/x86_64/kernel-modules-4.18.0-553.5.1.el8_lustre.x86_64.rpm --no-check-certificate
          wget -O /var/log/coral/build_cache/open/iso_cache/lustre_release/RPMS/x86_64/lustre-2.15.5-1.el8.x86_64.rpm https://downloads.whamcloud.com/public/lustre/lustre-2.15.5/el8.10/server/RPMS/x86_64/lustre-2.15.5-1.el8.x86_64.rpm --no-check-certificate
          wget -O /var/log/coral/build_cache/open/iso_cache/lustre_release/RPMS/x86_64/kmod-lustre-2.15.5-1.el8.x86_64.rpm https://downloads.whamcloud.com/public/lustre/lustre-2.15.5/el8.10/server/RPMS/x86_64/kmod-lustre-2.15.5-1.el8.x86_64.rpm --no-check-certificate
          wget -O /var/log/coral/build_cache/open/iso_cache/lustre_release/RPMS/x86_64/lustre-iokit-2.15.5-1.el8.x86_64.rpm https://downloads.whamcloud.com/public/lustre/lustre-2.15.5/el8.10/server/RPMS/x86_64/lustre-iokit-2.15.5-1.el8.x86_64.rpm --no-check-certificate
          wget -O /var/log/coral/build_cache/open/iso_cache/e2fsprogs_release/RPMS/x86_64/e2fsprogs-1.47.1-wc1.el8.x86_64.rpm https://downloads.whamcloud.com/public/e2fsprogs/1.47.1.wc1/el8/RPMS/x86_64/e2fsprogs-1.47.1-wc1.el8.x86_64.rpm --no-check-certificate
          wget -O /var/log/coral/build_cache/open/iso_cache/e2fsprogs_release/RPMS/x86_64/e2fsprogs-libs-1.47.1-wc1.el8.x86_64.rpm https://downloads.whamcloud.com/public/e2fsprogs/1.47.1.wc1/el8/RPMS/x86_64/e2fsprogs-libs-1.47.1-wc1.el8.x86_64.rpm --no-check-certificate
          wget -O /var/log/coral/build_cache/open/iso_cache/e2fsprogs_release/RPMS/x86_64/libcom_err-devel-1.47.1-wc1.el8.x86_64.rpm https://downloads.whamcloud.com/public/e2fsprogs/1.47.1.wc1/el8/RPMS/x86_64/libcom_err-devel-1.47.1-wc1.el8.x86_64.rpm --no-check-certificate
          wget -O /var/log/coral/build_cache/open/iso_cache/e2fsprogs_release/RPMS/x86_64/e2fsprogs-static-1.47.1-wc1.el8.x86_64.rpm https://downloads.whamcloud.com/public/e2fsprogs/1.47.1.wc1/el8/RPMS/x86_64/e2fsprogs-static-1.47.1-wc1.el8.x86_64.rpm --no-check-certificate
          wget -O /var/log/coral/build_cache/open/iso_cache/e2fsprogs_release/RPMS/x86_64/libss-1.47.1-wc1.el8.x86_64.rpm https://downloads.whamcloud.com/public/e2fsprogs/1.47.1.wc1/el8/RPMS/x86_64/libss-1.47.1-wc1.el8.x86_64.rpm --no-check-certificate
          wget -O /var/log/coral/build_cache/open/iso_cache/e2fsprogs_release/RPMS/x86_64/e2fsprogs-devel-1.47.1-wc1.el8.x86_64.rpm https://downloads.whamcloud.com/public/e2fsprogs/1.47.1.wc1/el8/RPMS/x86_64/e2fsprogs-devel-1.47.1-wc1.el8.x86_64.rpm --no-check-certificate
          wget -O /var/log/coral/build_cache/open/iso_cache/e2fsprogs_release/RPMS/x86_64/libcom_err-1.47.1-wc1.el8.x86_64.rpm https://downloads.whamcloud.com/public/e2fsprogs/1.47.1.wc1/el8/RPMS/x86_64/libcom_err-1.47.1-wc1.el8.x86_64.rpm --no-check-certificate
          wget -O /var/log/coral/build_cache/open/iso_cache/e2fsprogs_release/RPMS/x86_64/libss-devel-1.47.1-wc1.el8.x86_64.rpm https://downloads.whamcloud.com/public/e2fsprogs/1.47.1.wc1/el8/RPMS/x86_64/libss-devel-1.47.1-wc1.el8.x86_64.rpm --no-check-certificate
          ./cbuild build --debug=True             

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: artifacts-${{ matrix.label }}
          path: ./coral-*
      - name: Upload logs
        uses: actions/upload-artifact@master
        if: ${{ always() }}  # Upload logs regardless of whether the build failed or not
        with:
          name: logs-${{ matrix.label }}
          path: ./coral_build_*/*.log
